name: CI
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      spark_sdk_ref:
        description: 'Spark SDK commit/tag/branch reference'
        required: false
        type: string
        default: 'main'
  workflow_call:
    inputs:
      spark_sdk_ref:
        description: 'Spark SDK commit/tag/branch reference'
        required: false
        type: string
        default: 'main'

jobs:
  build:
    runs-on: macOS-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 🏗️ Check-out glow repository
        uses: actions/checkout@v5
        with:
          path: 'glow'

      - name: 🏗️ Setup spark-sdk repository
        uses: actions/checkout@v5
        with:
          repository: 'breez/spark-sdk'
          ssh-key: ${{ secrets.REPO_SSH_KEY }}
          path: 'spark-sdk'
          ref: ${{ inputs.spark_sdk_ref || 'main' }}

      - name: 🏗️ Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🏗️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.41.6'
          cache: true

      - name: Install rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "27.2"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up just
        uses: extractions/setup-just@v3

      - name: 📦 Install Spark SDK dependencies
        working-directory: spark-sdk/packages/flutter
        run: |
          just clean
          just setup

      - name: 📦 Install flutter_rust_bridge_codegen dependencies
        working-directory: spark-sdk/packages/flutter
        run: just frb

      - name: Generate Dart/Flutter bindings
        working-directory: spark-sdk/packages/flutter
        continue-on-error: true
        run: just gen

      - name: 📦 Install Flutter dependencies
        working-directory: glow
        run: flutter pub get

      - name: 🔍 Perform static analysis
        working-directory: glow
        run: dart analyze --fatal-infos

      - name: Check Formatting
        working-directory: glow
        run: dart format -o none --set-exit-if-changed -l 100 .
